# Generated by Django 5.1.3 on 2024-12-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
