# Generated by Django 5.1.3 on 2024-12-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default=None, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='subject',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='college_project_api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(default=None, related_name='student', to='college_project_api.subject'),
        ),
    ]
