# Generated by Django 5.1.3 on 2024-12-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0004_faculty_email_faculty_first_name_faculty_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField()),
                ('created_by', models.IntegerField()),
                ('deleted_on', models.DateField()),
                ('deleted_by', models.IntegerField()),
                ('modified_on', models.DateField()),
                ('modified_by', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default=None, upload_to='static/img')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('dob', models.DateField(default=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=50)),
                ('blood_group', models.CharField(default=None, max_length=50)),
                ('contact_number', models.BigIntegerField(default=None)),
                ('address', models.CharField(default=None, max_length=5)),
                ('created_on', models.DateField()),
                ('created_by', models.IntegerField()),
                ('deleted_on', models.DateField()),
                ('deleted_by', models.IntegerField()),
                ('modified_on', models.DateField()),
                ('modified_by', models.IntegerField()),
                ('subject', models.ManyToManyField(default=None, related_name='students', to='college_project_api.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('created_on', models.DateField()),
                ('created_by', models.IntegerField()),
                ('deleted_on', models.DateField()),
                ('deleted_by', models.IntegerField()),
                ('modified_on', models.DateField()),
                ('modified_by', models.IntegerField()),
                ('student', models.ManyToManyField(default=None, related_name='students', to='college_project_api.students')),
                ('subject', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='college_project_api.subjects')),
            ],
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
