# Generated by Django 5.1.3 on 2024-12-01 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0005_subjects_remove_student_subject_students_faculties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='deleted_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='modified_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='blood_group',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='deleted_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='modified_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='students',
            name='subject',
            field=models.ManyToManyField(related_name='students', to='college_project_api.subjects'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='deleted_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='modified_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
