# Generated by Django 5.1.3 on 2024-12-01 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0006_alter_faculties_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='student',
            field=models.ManyToManyField(related_name='students', to='college_project_api.students'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='college_project_api.subjects'),
        ),
    ]
