# Generated by Django 5.1.3 on 2024-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0007_alter_faculties_email_alter_faculties_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
