# Generated by Django 5.1.3 on 2024-12-02 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0013_alter_faculties_user_alter_students_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='students',
            name='deleted_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='students',
            name='modified_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
