# Generated by Django 5.1.3 on 2024-12-04 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0014_alter_students_created_on_alter_students_deleted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_on',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='deleted_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='deleted_on',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='modified_on',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
