# Generated by Django 5.1.3 on 2024-12-04 14:35

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0015_alter_students_created_by_alter_students_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='students',
            name='deleted_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='deleted_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='students',
            name='modified_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='modified_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='created_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='deleted_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='modified_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
