# Generated by Django 5.1.3 on 2024-12-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0017_alter_subjects_created_on_alter_subjects_deleted_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculties',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='students',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='students',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='students',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='students',
            name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='students',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='students',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='deleted_on',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='modified_on',
        ),
    ]
