# Generated by Django 5.1.3 on 2024-12-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0019_remove_students_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculties',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='user',
        ),
    ]
