# Generated by Django 5.1.3 on 2024-12-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0020_rename_subject_faculties_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='static/img')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('contact_number', models.BigIntegerField(default=None)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_project_api.role')),
                ('subjects', models.ManyToManyField(related_name='subjects', to='college_project_api.subjects')),
            ],
        ),
    ]
