# Generated by Django 5.1.3 on 2024-12-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_project_api', '0022_alter_faculties_email_alter_faculties_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(null=True, related_name='students', to='college_project_api.subjects'),
        ),
    ]
